[project]
name = "django-sprint3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asgiref==3.5.2",
    "attrs==22.2.0",
    "beautifulsoup4==4.11.2",
    "django==3.2.16",
    "django-bootstrap5==22.2",
    "faker==12.0.1",
    "flake8==5.0.4",
    "flake8-docstrings==1.7.0",
    "iniconfig==2.0.0",
    "mccabe==0.7.0",
    "mixer==7.2.2",
    "packaging==23.0",
    "pep8-naming==0.13.3",
    "pillow==9.3.0",
    "pluggy==1.0.0",
    "py==1.11.0",
    "pycodestyle==2.9.1",
    "pyflakes==2.5.0",
    "pytest==7.1.3",
    "pytest-django==4.5.2",
    "python-dateutil==2.8.2",
    "pytz==2022.7",
    "six==1.16.0",
    "sqlparse==0.4.3",
    "tomli==2.0.1",
    "yapf==0.32.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]

[project.scripts]
executive = 'seg:app'

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[tool.hatch.build.targets.wheel]
packages = ['seg']

[tool.mypy]
files = ['seg']
strict = true

[tool.ruff]
target-version = 'py313'
line-length = 80
fix = true
exclude = ['tests']

[tool.ruff.format]
quote-style = 'single'
docstring-code-format = false

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint]
select = [
    'A',    # flake8-builtins
    'ANN',  # flake8-annotations
    'B',    # flake8-bugbear
    'BLE',  # flake8-blind-except
    'C4',   # flake8-comprehensions
    'C90',  # maccabe
    'COM',  # flake8-commas
    'DJ',   # flake8-django
#    'D',    # pydocstyle
    'DTZ',  # flake8-datetimez
    'E',    # pycodestyle
    'ERA',  # flake8-eradicate
    'EXE',  # flake8-executable
    'F',    # pyflakes
    'FBT',  # flake8-boolean-trap
    'FLY',  # pyflint
    'FURB', # refurb
    'G',    # flake8-logging-format
    'I',    # isort
    'ICN',  # flake8-import-conventions
    'ISC',  # flake8-implicit-str-concat
    'LOG',  # flake8-logging
    'N',    # pep8-naming
    'PERF', # perflint
    'PGH',  # pygrep-hooks
    'PIE',  # flake8-pie
    'PLR',   # pylint
    'PT',   # flake8-pytest-style
    'PTH',  # flake8-use-pathlib
    'Q',    # flake8-quotes
    'RET',  # flake8-return
    'RSE',  # flake8-raise
    'RUF',  # ruff
    'S',    # flake8-bandit
    'SIM',  # flake8-simpify
    'SLF',  # flake8-self
    'SLOT', # flake8-slots
    'T100', # flake8-debugger
    'TRY',  # tryceratops
    'UP',   # pyupgrade
    'W',    # pycodestyle
    'YTT',  # flake8-2020
]

ignore = [
    'ANN401',   # dynamically typed expressions aren't a bad thing
    'COM812',   # trailing comma, conflicts with `ruff format`
    'ISC001',   # implicit string concat conflicts with `ruff format`
    'ISC003',   # prefer explicit string concat over implicit concat
    'PLR09',    # own complexity rules provided
    'PLC0414',  # alias as the og package to maky mypy happy
    'TRY003',   # long exception messages from `tryceratops`
    'D401',     # this rule always does false positives

    # conflicting rules
    'D203',     # prefer no blank line before class docstring
    'D213',     # prefer multiline summary being placed on ''' line
]

exclude = [
    '*/migrations/*'
]

external = ['WPS', 'DEP']

[tool.flake8]
# Configure WPS excludes
allowed-domain-names = [

]
ignore = [

]
per-file-ignores = [

]

[tool.deptry.per_rule_ignores]
DEP002 = [

]
